name: ArgoCD Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted  # Assuming this is a runner within your cluster

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd /usr/local/bin/argocd
          rm argocd
          argocd version --client

      - name: Set up port forwarding
        run: |
          kubectl port-forward svc/argocd-server -n argocd 8000:443 &
          echo $! > port_forward_pid
          sleep 5  # Give it a moment to establish the connection

      - name: Authenticate with ArgoCD
        env:
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          echo "Attempting to login to ArgoCD..."
          if ! argocd login localhost:8000 \
            --username "$ARGOCD_USERNAME" \
            --password "$ARGOCD_PASSWORD" \
            --insecure; then
            echo "ArgoCD login failed"
            exit 1
          fi
          echo "Login successful"
          argocd version

      - name: Sync Application
        run: |
          if ! argocd app sync trivial-dev --prune --self-heal; then
            echo "ArgoCD sync failed"
            exit 1
          fi
          echo "Sync completed successfully"

      - name: Wait for Sync
        run: |
          if ! argocd app wait trivial-dev --health --timeout 300; then
            echo "ArgoCD wait failed or timed out"
            exit 1
          fi
          echo "Application is healthy and fully synced"

      - name: Verify Deployment
        run: |
          argocd app get trivial-dev
          kubectl get pods -n argocd
          echo "Deployment verification completed"

      - name: Cleanup
        if: always()
        run: |
          if [ -f port_forward_pid ]; then
            kill $(cat port_forward_pid)
            rm port_forward_pid
          fi